name: test asdf plugin
on:
  push:

jobs:
  test_asdf_plugin:
    name: Run asdf plugin test
    runs-on: ubuntu-latest
    steps:
      - name: test asdf plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "tool-versions-to-env 3 shfmt_version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test_script:
    name: Test script returns correctly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Verify
        run: |
          OUTPUT=$(./bin/tool-versions-to-env 3 shfmt_version)
          if [ "$OUTPUT" -ne "3.4.2" ]; then
            exit 1
          fi